# Generated by Django 4.1.7 on 2023-03-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Input",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_record",
                    models.TimeField(auto_now_add=True, verbose_name="time"),
                ),
                (
                    "date_record",
                    models.DateTimeField(auto_now_add=True, verbose_name="date"),
                ),
                ("video", models.FileField(blank=True, upload_to="uploads/")),
                ("location", models.CharField(default="", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(blank=True, upload_to="uploads/")),
            ],
        ),
    ]
