# Generated by Django 4.1.7 on 2023-03-10 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_result_loop_alter_input_video_alter_result_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=9999)),
            ],
        ),
        migrations.AddField(
            model_name='input',
            name='note',
            field=models.CharField(default='', max_length=9999),
        ),
        migrations.AddField(
            model_name='input',
            name='traffic_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='input',
            name='weather',
            field=models.CharField(choices=[('sunny', 'Sunny'), ('cloudy', 'Cloudy'), ('rainy', 'Rainy'), ('snow', 'Snow'), ('windy', 'Windy'), ('partly cloudy', 'Partly cloudy'), ('fog', 'Fog')], default='null', max_length=999),
        ),
        migrations.AddField(
            model_name='result',
            name='input_video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='detection.input'),
        ),
        migrations.AlterField(
            model_name='input',
            name='location',
            field=models.CharField(default='', max_length=9999),
        ),
    ]
