# Generated by Django 4.1.7 on 2023-03-10 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_intersection_input_note_input_traffic_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='date_record',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 15, 38, 6, 440362, tzinfo=datetime.timezone.utc), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='input',
            name='time_record',
            field=models.TimeField(default=datetime.time(15, 38, 6, 440362), verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='input',
            name='weather',
            field=models.CharField(choices=[('sunny', 'Sunny'), ('cloudy', 'Cloudy'), ('rainy', 'Rainy'), ('snow', 'Snow'), ('windy', 'Windy'), ('partly cloudy', 'Partly cloudy'), ('fog', 'Fog'), ('null', 'Null')], default='null', max_length=999),
        ),
    ]
