# Generated by Django 4.1.7 on 2023-03-10 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_alter_input_date_record_alter_input_time_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='date_record',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='input',
            name='time_record',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='time'),
        ),
    ]
