# Generated by Django 4.1.7 on 2023-03-10 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0006_alter_input_date_record_alter_input_time_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='time_record',
            field=models.TimeField(default=datetime.datetime(2023, 3, 10, 15, 48, 10, 19189, tzinfo=datetime.timezone.utc), verbose_name='time'),
        ),
    ]
