# Generated by Django 4.1.7 on 2023-03-10 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0007_alter_input_time_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='time_record',
            field=models.TimeField(default=datetime.time(15, 52, 19, 606678), verbose_name='time'),
        ),
    ]
