# Generated by Django 4.1.7 on 2023-03-10 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0010_alter_input_location_alter_input_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='date_record',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='input',
            name='time_record',
            field=models.TimeField(default=django.utils.timezone.now, null=True, verbose_name='time'),
        ),
    ]
