# Generated by Django 4.1.7 on 2023-03-10 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0011_alter_input_date_record_alter_input_time_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='location',
            field=models.TextField(default='', max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='note',
            field=models.TextField(default='', max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='traffic_status',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
