# Generated by Django 4.1.7 on 2023-03-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0012_alter_input_location_alter_input_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='weather_choice',
            field=models.CharField(choices=[('sunny', 'Sunny'), ('cloudy', 'Cloudy'), ('rainy', 'Rainy'), ('snow', 'Snow'), ('windy', 'Windy'), ('partly cloudy', 'Partly cloudy'), ('fog', 'Fog'), ('null', 'Null')], max_length=14, null=True),
        ),
    ]
