# Generated by Django 4.1.7 on 2023-03-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0012_alter_input_location_alter_input_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='ownerName',
            field=models.CharField(default='', max_length=999),
        ),
    ]
