# Generated by Django 4.1.7 on 2023-03-11 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0013_alter_input_date_record_alter_input_time_record'),
        ('detection', '0013_input_ownername'),
    ]

    operations = [
    ]
