# Generated by Django 4.1.7 on 2023-03-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0013_input_ownername"),
    ]

    operations = [
        migrations.AddField(
            model_name="input",
            name="task_id",
            field=models.CharField(default="", max_length=999),
        ),
    ]
