# Generated by Django 4.1.7 on 2023-03-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0014_input_task_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="input",
            name="task_id",
        ),
    ]
