# Generated by Django 4.1.7 on 2023-03-11 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0015_alter_input_date_record_alter_input_time_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='intersection',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detection.intersection'),
        ),
    ]
