# Generated by Django 4.1.7 on 2023-03-25 15:14

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0015_remove_input_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='detect_status',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='input',
            name='intersection',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detection.intersection'),
        ),
        migrations.AlterField(
            model_name='input',
            name='date_record',
            field=models.DateField(default=datetime.datetime.now, null=True, verbose_name='date'),
        ),
    ]
