# Generated by Django 4.1.7 on 2023-03-25 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0016_input_detect_status_input_intersection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='date_upload',
            field=models.DateField(default=datetime.datetime.now, null=True, verbose_name='date_upload'),
        ),
    ]
