# Generated by Django 4.1.7 on 2023-03-13 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0016_input_time_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='detect_status',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
