# Generated by Django 4.1.7 on 2023-03-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0017_input_detect_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='date_record',
            field=models.DateTimeField(null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='input',
            name='time_record',
            field=models.TimeField(null=True, verbose_name='time'),
        ),
    ]
