# Generated by Django 4.1.1 on 2023-03-13 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0023_alter_input_date_record"),
    ]

    operations = [
        migrations.AlterField(
            model_name="input",
            name="date_record",
            field=models.DateField(
                default=datetime.datetime.now, null=True, verbose_name="date"
            ),
        ),
    ]
